export const SUBMITPROJECT_FILE_REQUEST = 'SUBMITPROJECT_FILE_REQUEST';
export const SUBMITPROJECT_FILE_SUCCESS = 'SUBMITPROJECT_FILE_SUCCESS';
export const SUBMITPROJECT_FILE_FAIL = 'SUBMITPROJECT_FILE_FAIL';

export const DOWNLOAD_FILES_REQUEST = 'DOWNLOAD_FILES_REQUEST';
export const DOWNLOAD_FILES_SUCCESS = 'DOWNLOAD_FILES_SUCCESS';
export const DOWNLOAD_FILES_FAIL = 'DOWNLOAD_FILES_FAIL';