export const GETSTUDENT_ENROLLMENT_REQUEST = 'GETSTUDENT_ENROLLMENT_REQUEST';
export const GETSTUDENT_ENROLLMENT_SUCCESS = 'GETSTUDENT_ENROLLMENT_SUCCESS';
export const GETSTUDENT_ENROLLMENT_FAIL = 'GETSTUDENT_ENROLLMENT_FAIL';

export const GETCOURSE_MODULE_REQUEST = 'GETCOURSE_MODULE_REQUEST';
export const GETCOURSE_MODULE_SUCCESS = 'GETCOURSE_MODULE_SUCCESS';
export const GETCOURSE_MODULE_FAIL = 'GETCOURSE_MODULE_FAIL';

export const GETUNIT_DETAILS_REQUEST = 'GETUNIT_DETAILS_REQUEST';
export const GETUNIT_DETAILS_SUCCESS = 'GETUNIT_DETAILS_SUCCESS';
export const GETUNIT_DETAILS_FAIL = 'GETUNIT_DETAILS_FAIL';