// create ProjExtnRequest

export const PROJECT_EXTENSION_REQUEST = 'PROJECT_EXTENSION_REQUEST';
export const PROJECT_EXTENSION_SUCCESS = 'PROJECT_EXTENSION_SUCCESS';
export const PROJECT_EXTENSION_FAIL = 'PROJECT_EXTENSION_FAIL';