export const GETQUESTION_DETAILS_REQUEST = 'GETQUESTION_DETAILS_REQUEST';
export const GETQUESTION_DETAILS_SUCCESS = 'GETQUESTION_DETAILS_SUCCESS';
export const GETQUESTION_DETAILS_FAIL = 'GETQUESTION_DETAILS_FAIL';

export const GETSTUDENT_SCORE_REQUEST = 'GETSTUDENT_SCORE_REQUEST';
export const GETSTUDENT_SCORE_SUCCESS = 'GETSTUDENT_SCORE_SUCCESS';
export const GETSTUDENT_SCORE_FAIL = 'GETSTUDENT_SCORE_FAIL';

export const STUDENTTEST_SUBMIT_REQUEST = 'STUDENTTEST_SUBMIT_REQUEST';
export const STUDENTTEST_SUBMIT_SUCCESS = 'STUDENTTEST_SUBMIT_SUCCESS';
export const STUDENTTEST_SUBMIT_FAIL = 'STUDENTTEST_SUBMIT_FAIL';